### 서브작업 ID 검색
GET {{domain}}/sub-task/id/{{subTaskId}}
Content-Type: application/json
Authorization: Bearer {{auth}}

### 서브작업 사용자 ID 검색
GET {{domain}}/sub-task/task/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{auth}}

### 서브작업 추가
POST {{domain}}/sub-task
Content-Type: application/json
Authorization: Bearer {{auth}}

{
    "projectId": {{projectId}},
    "taskId": {{taskId}},
    "priority": 2,
    "orderNo": 0,
    "name": "서브작업3"
}

### 서브작업 수정
PATCH {{domain}}/sub-task
Content-Type: application/json
Authorization: Bearer {{auth}}

{
    "id": {{subTaskId}},
    "taskId": {{taskId}},
    "priority": 3,
    "name": "서브작업(수정됨)"
}

### 서브작업 순서 수정
PATCH {{domain}}/sub-task/order
Content-Type: application/json
Authorization: Bearer {{auth}}

[
  { "id": 14, "orderNo": 1 },
  { "id": 15, "orderNo": 2 },
  { "id": 16, "orderNo": 3 }
]

### 서브작업 삭제
DELETE {{domain}}/sub-task
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "id": {{subTaskId}}
}