### 작업 ID 검색
GET {{domain}}/task/id/{{taskId}}
Content-Type: application/json

### 작업 사용자 ID 검색
GET {{domain}}/task/board/{{boardId}}?priority=2
Content-Type: application/json

### 작업 추가
POST {{domain}}/task
Content-Type: application/json

{
    "userId": {{userId}},
    "projectId": {{projectId}},
    "boardId": {{boardId}},
    "priority": 2,
    "orderNo": 2,
    "name": "철수작업"
}

### 작업 수정
PATCH {{domain}}/task/id/{{taskId}}
Content-Type: application/json

{
    "boardId": {{boardId}},
    "priority": 3,
    "name": "철수작업(수정됨)"
}

### 작업 순서 수정
PATCH {{domain}}/task/order
Content-Type: application/json

[
  { "id": 4, "orderNo": 1 },
  { "id": 5, "orderNo": 2 },
  { "id": 6, "orderNo": 3 },
  { "id": 7, "orderNo": 4 }
]

### 작업 삭제
DELETE {{domain}}/task/id/{{taskId}}
Content-Type: application/json