### 사용자 ID 검색
GET {{domain}}/user/id/{{userId}}
Content-Type: application/json

### 사용자 모두 검색
GET {{domain}}/user
Content-Type: application/json

### 사용자 추가
POST {{domain}}/user
Content-Type: application/json

{
    "providerId": "google",
    "profileImage": null,
    "email": "kim@gmail.com",
    "name": "김철수"
}

### 사용자 수정
PATCH {{domain}}/user/id/{{userId}}
Content-Type: application/json

{
  "name": "이영희"
}

### 사용자 삭제
DELETE {{domain}}/user/id/{{userId}}
Content-Type: application/json